export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  RELIC_NOT_FOUND: "RELIC_NOT_FOUND",
  DAMAGE_NOT_FOUND: "DAMAGE_NOT_FOUND",
  PLAN_NOT_SUBMITTABLE: "PLAN_NOT_SUBMITTABLE",
  PLAN_NOT_DECIDABLE: "PLAN_NOT_DECIDABLE",
  PLAN_BASIS_STALE: "PLAN_BASIS_STALE",
  PLAN_DUPLICATE_EXPERT: "PLAN_DUPLICATE_EXPERT",
  PLAN_QUORUM_MISMATCH: "PLAN_QUORUM_MISMATCH"
} as const;
