export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  RELIC_NOT_FOUND: "RELIC_NOT_FOUND",
  DAMAGE_NOT_FOUND: "DAMAGE_NOT_FOUND",
  PLAN_NOT_SUBMITTED: "PLAN_NOT_SUBMITTED",
  BASIS_STALE: "BASIS_STALE",
  EXPERT_DUPLICATE: "EXPERT_DUPLICATE",
  APPROVAL_THRESHOLD: "APPROVAL_THRESHOLD"
} as const;
